# Generated by Django 4.2.3 on 2023-07-26 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreArea', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCentro', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCliente', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoContrato', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=15)),
                ('idArea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.area')),
                ('idCentro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.centro')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreRegion', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoAlerta', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoTurno', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateField()),
                ('fechaTermino', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreZona', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=15)),
                ('inasistencias', models.IntegerField()),
                ('horasTotales', models.IntegerField()),
                ('horasExtras', models.IntegerField()),
                ('vacaciones', models.IntegerField()),
                ('licencia', models.IntegerField()),
                ('valorHora', models.IntegerField()),
                ('horasCont', models.IntegerField()),
                ('horasObj', models.IntegerField()),
                ('turnosTrab', models.IntegerField()),
                ('bonoColacion', models.IntegerField()),
                ('bonoMov', models.IntegerField()),
                ('bonoResp', models.IntegerField()),
                ('idArea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.area')),
                ('idCargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cargo')),
                ('idCentro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.centro')),
                ('idContrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.contrato')),
                ('idCoordinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.coordinador')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sueldoBase', models.IntegerField()),
                ('gratificacion', models.IntegerField()),
                ('horaExtra', models.IntegerField()),
                ('bonos', models.IntegerField()),
                ('aguinaldo', models.IntegerField()),
                ('vacaciones', models.IntegerField()),
                ('viatico', models.IntegerField()),
                ('asignacionFamiliar', models.IntegerField()),
                ('colacion', models.IntegerField()),
                ('movilizacion', models.IntegerField()),
                ('salaCuna', models.IntegerField()),
                ('totalHaberes', models.IntegerField()),
                ('totalImponible', models.IntegerField()),
                ('afp', models.IntegerField()),
                ('isapre', models.IntegerField()),
                ('fonasa', models.IntegerField()),
                ('segCes', models.IntegerField()),
                ('imptoUnico', models.IntegerField()),
                ('ctaAfp', models.IntegerField()),
                ('anticipos', models.IntegerField()),
                ('descuento', models.IntegerField()),
                ('ley3', models.IntegerField()),
                ('totalDescuento', models.IntegerField()),
                ('liquido', models.IntegerField()),
                ('fechaPago', models.DateField()),
                ('idProfesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profesional')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('fechaInicioAtencion', models.DateField()),
                ('vigente', models.BooleanField()),
                ('gasto', models.IntegerField()),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
                ('idCoordinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.coordinador')),
                ('idRegion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.region')),
                ('idTipoTurno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tipoturno')),
                ('idZona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.zona')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaAsistencia', models.DateField()),
                ('asisteProfesional', models.BooleanField()),
                ('estado', models.IntegerField()),
                ('horas', models.IntegerField()),
                ('movilizacion', models.IntegerField()),
                ('colacion', models.IntegerField()),
                ('idPaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.paciente')),
                ('idProfesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profesional')),
            ],
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaAlerta', models.DateField()),
                ('descripcion', models.CharField(max_length=200)),
                ('idAsistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.asistencia')),
                ('idPaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.paciente')),
                ('idProfesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profesional')),
                ('idTipoAlerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tipoalerta')),
            ],
        ),
    ]
